require_relative 'the_meaning_of_programs/big_step'
require_relative 'the_meaning_of_programs/denotational'
require_relative 'the_meaning_of_programs/small_step'
require_relative 'the_meaning_of_programs/syntax'
