require_relative 'finite_automata/dfa'
require_relative 'finite_automata/dfa_design'
require_relative 'finite_automata/dfa_rulebook'
require_relative 'finite_automata/fa_rule'
require_relative 'finite_automata/nfa'
require_relative 'finite_automata/nfa_design'
require_relative 'finite_automata/nfa_rulebook'
require_relative 'finite_automata/nfa_simulation'
